name: pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload your page as github pages artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: dist

  deploy:
    needs: build
    environment:
      name: github-pages
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    concurrency:
      group: pages
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to pages branch
        uses: actions/deploy-pages@v4